color: orange
fieldLayouts:
  a7dccbfb-9897-496b-87c4-0648922bffc1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-06T06:09:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 82bdee86-3536-445f-b250-d686895c44f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T06:09:50+00:00'
            elementCondition: null
            fieldUid: 32972c85-b85e-45de-a6a1-d58a643d3e81 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8cc392ab-ff4b-4b62-bd9b-e115782e6680
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-13T08:52:27+00:00'
            elementCondition: null
            fieldUid: fd9de71f-2359-42e6-a1ae-9cd9a96a905c # About Us Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96b477d0-e902-4291-8aeb-2cd2ab2dc811
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T06:09:50+00:00'
            elementCondition: null
            fieldUid: 3ae65c29-e9b0-4b1c-a365-d56e5b103f40 # Button
            handle: button1
            includeInCards: false
            instructions: null
            label: 'Button - 1'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12a26bdf-8b61-41c1-9eee-27316fa70d8b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-10T07:04:06+00:00'
            elementCondition: null
            fieldUid: 011c1877-d25c-449b-a386-644c09336017 # Social Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad9c59b6-09d0-4ff2-82dd-c1e04257d5e7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T06:09:50+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 15c12752-9eff-49fa-8521-991d5157b595
            userCondition: null
          -
            dateAdded: '2024-11-06T06:52:15+00:00'
            elementCondition: null
            fieldUid: 4060ca93-4d55-48ba-be72-11fd85105282 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33f5936a-5dc8-41ad-b652-9fb34ea724dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-06T06:09:50+00:00'
            elementCondition: null
            fieldUid: 3ae65c29-e9b0-4b1c-a365-d56e5b103f40 # Button
            handle: button2
            includeInCards: false
            instructions: null
            label: 'Button - 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1344ff51-4a3d-4f6b-9cf6-ea564b01ba8f
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 951861e9-b1ea-4086-8932-a98070a312b7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-06T06:09:50+00:00'
            elementCondition: null
            fieldUid: aecb8bb2-c511-458e-98c9-73c2e6fa9c7d # Layout - Heading + Text
            handle: layout
            includeInCards: false
            instructions: null
            label: Layout
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a96e6c11-ace9-4224-954e-e9468fa7d82e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-06T06:09:50+00:00'
            elementCondition: null
            fieldUid: b8cf975c-8b0e-4f79-968b-ae246d2f8bf1 # Padding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4eebe002-21bb-408c-a120-40a7394c3865
            userCondition: null
            warning: null
            width: 50
        name: 'Block Settings'
        uid: c40fe419-5b6c-4730-8a72-0bdabd9decf1
        userCondition: null
handle: headingText
hasTitleField: false
icon: text
name: 'Heading + Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
