columnSuffix: null
handle: urlLink
instructions: null
name: 'URL Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
    - email
    - entry
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
