dateModified: 1731619816
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      heading: Pages
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:7b662bcd-ea91-4c91-86ce-c60348c664d1' # Page
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      heading: Content
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:f656c554-7cc9-4ff7-95e1-d8b359ec894c' # Blog
      tableAttributes:
        - status
        - postDate
        - authors
        - link
      type: native
    -
      key: 'section:e1170ac2-9f83-451a-92da-52a8e324f98e' # Case Studies
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:31370897-985c-4000-80ba-25963b89b6bb' # FAQ
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:4a8338c2-82b0-433a-8180-45877510d28d' # Fleet
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      key: 'section:b24beb43-c574-494f-b131-1b256743f9a6' # Services
      type: native
    -
      heading: Globals
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - status
        - link
      type: native
email:
  fromEmail: $CRAFT_SYSTEM_EMAIL
  fromName: $CRAFT_SYSTEM_EMAIL
  replyToEmail: null
  template: _emails/system.twig
  transportSettings:
    apiKey: $MAILGUN_API_KEY
    domain: $MAILGUN_DOMAIN
    endpoint: $MAILGUN_ENDPOINT
  transportType: craft\mailgun\MailgunAdapter
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: $ASSETS_FILES_PATH
    type: craft\fs\Local
    url: $ASSETS_FILES_URL
  images:
    hasUrls: true
    name: Images
    settings:
      path: $ASSETS_IMAGES_PATH
    type: craft\fs\Local
    url: $ASSETS_IMAGES_URL
meta:
  __names__:
    0cb5f968-0499-4ffe-9f81-0804be95a62e: 'Fleet Grid' # Fleet Grid
    0ff0054d-4429-4d13-b8e8-8428703d8525: 'Link - Dropdown Fleet' # Link - Dropdown Fleet
    1ce5d7a8-5af2-497b-974f-b6ae78207980: 'Case Study - Category' # Case Study - Category
    1e0dce05-0565-453d-b0d0-cd82001c94ee: 'Blog Tag' # Blog Tag
    2ba16f27-936a-48f5-b959-fe68ebfed2bf: 'Text Excerpt' # Text Excerpt
    2cc6717d-71f5-45d3-aebf-50bf55edbbed: 'Trustpilot Cards' # Trustpilot Cards
    2d951d16-cd0c-4fb8-81ae-abedbf7518bc: New # New
    2defe1a4-7f17-4178-953c-b8dec8400673: Date # Date
    2e3c4108-1411-475f-91e0-aea4ece9866d: 'Button - Brand' # Button - Brand
    2e9c6a7b-2f62-436b-a6d8-004629a97ade: 'Quote Progress Text' # Quote Progress Text
    2e482ae0-dadb-4ec6-800a-74b02b393492: 'FAQ - Answer' # FAQ - Answer
    2ebbb508-ca11-4955-8294-a5fe29059265: Form # Form
    2ec883fa-306f-43aa-9106-cff3e6d1af50: 'Social Links' # Social Links
    3ae65c29-e9b0-4b1c-a365-d56e5b103f40: Button # Button
    3ce0ab58-6a6b-49a8-96c5-412dc9ae77f1: 'USP Cards' # USP Cards
    3ea47485-f5ba-4aa3-952e-e0f5283984c7: 'Phone Number' # Phone Number
    4a8338c2-82b0-433a-8180-45877510d28d: Fleet # Fleet
    4ae8e042-ab6e-4b2b-b674-edcd7a01d4b8: Office # Office
    4ba88fea-0529-4641-8cb3-08d825a4faf1: 'FAQ Entries' # FAQ Entries
    04c4f46d-ac8f-435c-843c-320f0fb582ac: 'Text + Icon Card' # Text + Icon Card
    4ddfdf96-b71c-4a70-826e-4b46188161a3: Theme # Theme
    4ded74db-fc6a-440e-b267-80bfdc4feabd: contactnumber # contactnumber
    04e1c8bd-fe67-47db-9064-8610c35b6816: 'Info Slide' # Info Slide
    5d33a21b-85a2-4c5c-9bb0-b484b7403eca: 'Custom Dark' # Custom Dark
    5ed04731-7e6c-40fb-b4b6-f495b43bc5eb: OMC # OMC
    5eefdcdd-6407-4cd7-9ce4-0055574620d9: FAQ # FAQ
    6b4b9c25-2523-4f11-94ee-c0d6ef63eae0: 'Author Image' # Author Image
    6c89002f-6f56-4832-8037-fbc0763d6723: 'Case Study' # Case Study
    6e423f8b-75dd-4936-9837-37c0a49402b6: 'Slider Images' # Slider Images
    06f62e16-fd59-4822-ae44-f6e3d5367237: Quote # Quote
    06f96a04-0e92-4dd7-81dd-39718294791d: Offices # Offices
    7a3a53b0-aefc-4c7f-a3fc-b890fe021391: 'Fleet Slider' # Fleet Slider
    7b662bcd-ea91-4c91-86ce-c60348c664d1: Page # Page
    7c337caf-5d8f-4a66-9662-a698ceedbe96: 'Trustpilot - Text' # Trustpilot - Text
    7c420a89-cf98-4c48-b38f-64793c3047f0: 'Page - Quote' # Page - Quote
    7c623de7-69c8-4ab1-a871-85996cd33921: 'Custom Light' # Custom Light
    7d6c9f84-aee0-4b21-b095-cefc4e59987a: 'choose Us' # choose Us
    7e2defb7-ea6e-4c6b-bcf2-e146804bc1c6: 'Quote Progress' # Quote Progress
    7eb63953-9330-4c6a-9fe9-3d11b06655ba: 'Light Switch' # Light Switch
    8b610edc-f2dd-46b6-9597-96fcbb6d302a: Simple # Simple
    08c386f4-5a41-4c9f-8282-f6785af06bfc: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    8d34ac83-d60e-4c48-9004-da40628cc6dd: 'Service Selector Item' # Service Selector Item
    08f6274d-3c73-407b-82ac-6cf8d0dcffcb: Full # Full
    9cb6c70d-ea55-4615-80b7-ddb3d924d165: 'Header Navigation' # Header Navigation
    9cecf014-0859-4c02-88fc-2f12bda2e735: 'FAQ - Question' # FAQ - Question
    9e5f4051-5fb7-4266-9b16-a2ba63704dbe: 'Author Name' # Author Name
    011c1877-d25c-449b-a386-644c09336017: 'Social Links' # Social Links
    13c1aa4b-e319-4318-89d6-6d9706cbb7ff: 'Fleet Tag' # Fleet Tag
    16f0b21a-80bb-448e-8e45-e4fe7fc8d4af: 'Text + Icon Cards' # Text + Icon Cards
    19d6d897-1cde-4d59-914a-2bf8a23e7916: 'Public Schema' # Public Schema
    20dc9d31-8659-4d8e-8e2f-578b7cf5c6a6: Heading # Heading
    21db55fe-231d-42ce-a731-a1594256cbc2: 'Rich Text' # Rich Text
    26fb68a7-68a1-41cc-8216-6658d0458588: 'Dropdown Cards' # Dropdown Cards
    31f99b09-7d43-4a28-8bb0-bf33ff1ecc56: 'Service Grid' # Service Grid
    32f943b3-1429-40be-9171-55e40a0186ba: 'Page - Blog Exterior' # Page - Blog Exterior
    36dcd8c0-5c8d-4973-aff0-6549948c8135: 'Author Country' # Author Country
    38b2c1bd-af85-4e3f-a0e8-572d2bb16fb0: Image # Image
    42a1d5e2-cef8-4525-8160-7926a3f648ac: 'Font Awesome' # Font Awesome
    46c2f4e6-a65a-4cbd-9962-ad4f8aabd801: 'choose us cards' # choose us cards
    53c480df-d338-438c-b3ef-bbcc64cef008: 'Text Icon' # Text Icon
    67f3a8e1-fb07-4135-9632-b9d51eb53605: 'Footer Text' # Footer Text
    75c306ea-9ac0-4a6d-afff-f7272e345bda: 'About Section' # About Section
    77c19ebd-f9b9-4505-93be-58e538528e16: Files # Files
    78a09d8b-4266-4390-8f44-79f22ecfea14: Globals # Globals
    82c54e9a-5472-4399-8f54-8ce7367fb144: 'Page - Text + Nav' # Page - Text + Nav
    83e2bb23-12d2-4bbc-87a2-fb663976f6d0: 'Dropdown Card' # Dropdown Card
    86b0adf0-5bb4-4cc3-b597-b32bd746081e: 'Rich Text - Full' # Rich Text - Full
    89e258ef-b030-465c-917d-eaaf04e5ab9e: 'Rich Text - Simple' # Rich Text - Simple
    102e50e8-7d25-40ec-b71a-e6e8c8550f66: 'USP Card' # USP Card
    198fdf84-69c1-46e2-925e-74c9e934325c: 'Case Study' # Case Study
    221a3e88-bf37-4ec3-8b78-bb2262608fd5: 'Heading + Text' # Heading + Text
    291b8794-da4b-44d3-b993-50203f9590b6: Gallery # Gallery
    0327abbb-31d6-4f68-ba72-ac7e0fccba33: 'Footer Navigation Columns' # Footer Navigation Columns
    0485aae5-16d7-4a38-a336-f9d6755a4641: 'Rating & Reviews Card' # Rating & Reviews Card
    491c947f-f0c2-4cd5-8908-c5f5eb7ac781: 'Scrolling Text' # Scrolling Text
    673b7afa-9d17-452e-bbda-b389beeaa2e0: 'Page - Case Studies Exterior' # Page - Case Studies Exterior
    735cd1c0-1a58-4cc8-b37e-7275a35e8886: 'Image Row Images' # Image Row Images
    803cdff6-4499-4c9c-b7f8-a204015301dc: 'Service Entry' # Service Entry
    921eb901-c785-406a-87fb-b54b918b699c: 'choose us cards' # choose us cards
    969df201-73c4-4fed-8c7d-a02694ee1452: Video # Video
    1491fb3e-eafb-43b7-b01b-4614e405777c: 'Body Content Builder' # Body Content Builder
    1883d118-46e9-48f4-92d8-ae7f8933e7e3: 'Main Heading' # Main Heading
    3620aee4-a68e-4e66-92aa-2e8cd6c88d75: 'Choose us text' # Choose us text
    4042cf96-2c15-4dee-9164-d02e70bbc45d: ' Fleet Detail' #  Fleet Detail
    4060ca93-4d55-48ba-be72-11fd85105282: Image # Image
    32972c85-b85e-45de-a6a1-d58a643d3e81: Heading # Heading
    49163c94-0c7c-4a8e-a5e6-3a46e8122ddb: 'Rating & Reviews Section' # Rating & Reviews Section
    64700cdf-f2e4-4360-a2b6-a7433e0da135: 'Scrolling Text' # Scrolling Text
    75251b3a-7876-48bb-8719-9bb34b84a0e0: 'Navigation Column' # Navigation Column
    78647ab1-8c52-45e0-aff2-3232685b4ee5: 'Assets - Images' # Assets - Images
    00302146-bb35-41e6-9c93-8ee41d18600a: FAQ # FAQ
    319101f5-883c-43f3-bb97-a96d26b34139: 'Fleet Nav Entries' # Fleet Nav Entries
    379979f8-8b8a-4d0e-be50-cf55272ecf6c: Hero # Hero
    574887d5-533e-47d7-a279-69eb6584799a: 'Contact Form' # Contact Form
    787967f0-9a61-4502-9ec1-b413d02b9279: 'Meta & Social Data' # Meta & Social Data
    792186a9-e18c-4d1e-8409-503bae851035: 'Availability ' # Availability 
    796547c9-f257-4cd2-bd77-3857328c6f01: 'Quote Text' # Quote Text
    08255804-15c4-4dab-a60b-2b98d3942b27: 'Slider Image' # Slider Image
    18712986-f171-4da5-b3c5-e99c0b07c90b: 'Paragraph Text' # Paragraph Text
    25805867-ef92-410d-965e-77956fadaf44: 'URL Link' # URL Link
    31370897-985c-4000-80ba-25963b89b6bb: FAQ # FAQ
    53236171-064e-472b-9cbf-3a6e4b37edbd: 'Blog Tag' # Blog Tag
    63357992-55e3-42bf-80a7-0c5fcca253d4: 'Services Image Text' # Services Image Text
    65101654-dcea-4e79-9016-9eba89748445: 'FAQ Profile Image' # FAQ Profile Image
    75794816-59b0-4813-b5a5-311173879c8c: USP # USP
    86899528-1337-4454-925f-173f3a7861de: 'Gallery Images' # Gallery Images
    a73ff666-efd5-4174-89cb-4ede7baa870c: Globals # Globals
    a825bcf0-1760-4d77-b097-f008cdb60d54: 'Page - Contact' # Page - Contact
    aa2a3523-7407-4594-aa69-60db7b1ad98e: Quote # Quote
    accd1fcb-b9ba-4c5e-b586-e40e58daea71: 'Staggered Blocks' # Staggered Blocks
    ad4eda2e-00bd-445a-9c4c-c7a920870ebf: 'Video URL' # Video URL
    aecb8bb2-c511-458e-98c9-73c2e6fa9c7d: 'Layout - Heading + Text' # Layout - Heading + Text
    b010ea5f-e470-4615-b1b3-8694b4b92396: 'Plain Text - Multiline' # Plain Text - Multiline
    b8cf975c-8b0e-4f79-968b-ae246d2f8bf1: Padding # Padding
    b8eca6bf-5f77-4e26-afb4-b61841f2fea1: 'Button - No Text' # Button - No Text
    b24beb43-c574-494f-b131-1b256743f9a6: Services # Services
    b56e15cb-a4a9-4e41-b17a-86992ce0e05e: 'Hero Background' # Hero Background
    b85568a4-73fb-48e5-9348-39aba103ded5: 'Hero Quote Title' # Hero Quote Title
    bdf6317d-0df7-449f-a937-a1a274ffb106: 'Page - Blocks' # Page - Blocks
    bf1b5716-c9c3-4a8a-9304-dfe36409e9a0: 'Faces Images' # Faces Images
    c2fb95e7-1e74-4227-aa8c-d4047c9b59f9: 'Rating & Reviews' # Rating & Reviews
    c6a736fe-4c28-4127-8e44-57ec4ba836cd: 'Trustpilot Card' # Trustpilot Card
    c29f12ad-07c4-45ab-a0e2-ea570b18326e: 'Link - Dropdown Cards' # Link - Dropdown Cards
    cb5451de-7ba9-4d1a-a1e8-a521c12cf67b: 'Service Short Title' # Service Short Title
    cb87554f-d2ed-4a0f-81ad-32f9832f7865: 'Fleet Tag' # Fleet Tag
    cf08515e-fc2b-4b56-bd6d-70d5f33a049b: 'Hero - Quote' # Hero - Quote
    d67ffd7a-0f91-474d-99e3-9f9ec85fbe16: Service # Service
    d99bf7af-1eb1-4b77-814e-624eeec1a0e3: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    d489f8dd-57fc-4afb-8886-2c95fb4a7bfd: 'Service Selector' # Service Selector
    d640a2ab-e813-42e1-aeee-69524da7ecaa: 'Fleet Information' # Fleet Information
    d671fd86-cab7-4360-b1ec-0a993aaddef8: 'Text + FAQ' # Text + FAQ
    d8199001-471d-45a5-bf7d-89514438e478: Images # Images
    dee0e12a-d0be-4dce-864e-96f853d767f2: 'Plain Text' # Plain Text
    df10c92e-5039-4a9f-b9f0-ec8193e92a7e: Link # Link
    e21e545b-038e-4468-aa8f-237310d0a026: 'Staggered Block' # Staggered Block
    e47e78ea-7cd0-4cc6-988b-f68b3801cd66: 'Entry Title' # Entry Title
    e83e6aa5-9902-400e-8be8-597cc58b849e: 'Brand Icon' # Brand Icon
    e95b14f5-b435-4149-b65f-9dafd6231f8a: 'Text + Icon Cards' # Text + Icon Cards
    e948bd0f-e834-4571-bb8c-6932248c5c35: 'Assets - Files' # Assets - Files
    e1170ac2-9f83-451a-92da-52a8e324f98e: 'Case Studies' # Case Studies
    eb0d43f1-1fed-435f-93ce-8e284d0b317f: 'Star Rating' # Star Rating
    eb7ba0c1-3129-4cdf-ac5b-c3b67462601a: 'Info Slider' # Info Slider
    f0c3bd54-deee-4341-af79-8badf1af0e17: 'Gallery Image' # Gallery Image
    f00435c2-516d-4d32-bb6e-a525ffcc9019: 'Image Slider' # Image Slider
    f0337310-b49a-4d17-bfa5-a60cbea3c0b3: 'Fleet Entries' # Fleet Entries
    f05b9e1f-df26-4fbb-a236-f9b60ca23ba4: 'Quote Progress' # Quote Progress
    f2c22533-32b6-4c64-afdf-1ecd17a508fa: 'Quote Progress Title' # Quote Progress Title
    f4bd1639-9234-4d2b-a20d-54dd25cbd843: 'Image Row' # Image Row
    f7a459f6-1d4b-4655-bcc9-f2eec0df4844: 'Hero - Text' # Hero - Text
    f9b7d774-c1a4-494c-963f-a5710417d6c8: 'Aspect Ratio' # Aspect Ratio
    f99b2c78-3761-43e9-873a-6f90c5fe9855: Links # Links
    f527ca98-8954-48d2-97a6-c1cd44f86c42: 'Staggered Blocks' # Staggered Blocks
    f582ebb4-1ff9-4092-b7d1-37d579a4ea68: Article # Article
    f656c554-7cc9-4ff7-95e1-d8b359ec894c: Blog # Blog
    f690c21a-3bdd-46f9-b578-059ebc2b8e8d: 'Rating & Reviews Cards' # Rating & Reviews Cards
    f693e845-ded2-4966-ab74-bb6d4ca0d3c6: 'Number of' # Number of
    f873b65a-cad9-4540-968d-2693401774ae: 'Service Selector' # Service Selector
    f961ae4f-abe8-4842-b296-16d412036c48: 'Content Builder' # Content Builder
    fbee0cff-d22a-4a7b-80ce-8fb02e92ab6e: 'Case Study - Short Title' # Case Study - Short Title
    fc1bbb5a-6159-44dc-955f-ed71bdc2ca73: 'Icon Picker' # Icon Picker
    fd9de71f-2359-42e6-a1ae-9cd9a96a905c: 'About Us Text' # About Us Text
    ff57ce95-144f-4c6f-9d6d-f75daca3bf74: 'choose Us number' # choose Us number
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: ZGZJXF7QAS54ESRRGUWFOWIQ
    schemaVersion: 5.7.0.1
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  consume:
    edition: standard
    enabled: true
    licenseKey: 52CDVX2A7287LIQVXQP42LMP
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: GYK88ES8NEYGR0VIKOCX8BDC
    schemaVersion: 3.4.6
  hyper:
    edition: standard
    enabled: true
    licenseKey: ZRM3T4RVBQU9IVMMR1SF4RR9
    schemaVersion: 1.0.0
  icon-picker:
    edition: standard
    enabled: true
    licenseKey: JBCH9RMYAZCESSSPFQPM6HMD
    schemaVersion: 1.2.3
    settings:
      enableCache: true
      iconItemSize: 32
      iconItemSizeLarge: 40
      iconItemWrapperSize: 56
      iconItemWrapperSizeLarge: 72
      iconSetsPath: '@webroot/icon-picker/'
      iconSetsUrl: '@web/icon-picker/'
      redactorFieldHandle: ''
  imager-x:
    edition: pro
    enabled: true
    licenseKey: KHMOSLWBHXBQ5EC97AEDMZVI
    schemaVersion: 4.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    licenseKey: GJ66P67ZGY4ML0F9C6DHGJB7
    schemaVersion: 3.0.12
  seomatic:
    edition: standard
    enabled: true
    licenseKey: JMXU8QOG86XTHKJR4Q0X48RY
    schemaVersion: 3.0.12
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $CRAFT_SITE_NAME
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
