defaultPlacement: end
enableVersioning: true
entryTypes:
  - 198fdf84-69c1-46e2-925e-74c9e934325c # Case Study
handle: caseStudies
maxAuthors: 1
name: 'Case Studies'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: case-studies/_entry
    uriFormat: 'case-studies/{slug}'
type: channel
